name: Freelance actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build app
      - uses: actions/checkout@v2
      - run: mvn -Pdev clean install package
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: test app
      - uses: actions/checkout@v2
      - run: mvn test
